// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";
import { TwilioService, MockTwilioService, TwilioServiceWithMockVerify } from "@services/twilio.ts";

import JournalEntryConcept from "./JournalEntry/JournalEntryConcept.ts";
import CallWindowConcept from "./CallWindow/CallWindowConcept.ts";
import JournalPromptConcept from "./JournalPrompt/JournalPromptConcept.ts";
import CallSessionConcept from "./CallSession/CallSessionConcept.ts";
import UserConcept from "./User/UserConcept.ts";
import ReflectionSessionConcept from "./ReflectionSession/ReflectionSessionConcept.ts";
import PhoneCallConcept from "./PhoneCall/PhoneCallConcept.ts";
import CallSchedulerConcept from "./CallScheduler/CallSchedulerConcept.ts";
import ProfileConcept from "./Profile/ProfileConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import UserAuthenticationConcept from "./UserAuthentication/UserAuthenticationConcept.ts";

export type { default as JournalEntryConcept } from "./JournalEntry/JournalEntryConcept.ts";
export type { default as CallWindowConcept } from "./CallWindow/CallWindowConcept.ts";
export type { default as JournalPromptConcept } from "./JournalPrompt/JournalPromptConcept.ts";
export type { default as CallSessionConcept } from "./CallSession/CallSessionConcept.ts";
export type { default as UserConcept } from "./User/UserConcept.ts";
export type { default as ReflectionSessionConcept } from "./ReflectionSession/ReflectionSessionConcept.ts";
export type { default as PhoneCallConcept } from "./PhoneCall/PhoneCallConcept.ts";
export type { default as CallSchedulerConcept } from "./CallScheduler/CallSchedulerConcept.ts";
export type { default as ProfileConcept } from "./Profile/ProfileConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as UserAuthenticationConcept } from "./UserAuthentication/UserAuthenticationConcept.ts";

// Initialize the database connection
export const [db, client] = await getDb();

// Initialize Twilio service for SMS verification codes
const useMocks = Deno.env.get("USE_MOCKS") === "true";
const mockVerifyOnly = Deno.env.get("MOCK_TWILIO_VERIFY") === "true";

let twilioService;
if (useMocks) {
  console.log(`[Twilio] Initializing Mock Twilio service (USE_MOCKS=true)`);
  twilioService = new MockTwilioService();
} else if (mockVerifyOnly) {
  console.log(`[Twilio] Initializing Hybrid Twilio service - Real calls/SMS, Mock Verify (MOCK_TWILIO_VERIFY=true)`);
  twilioService = new TwilioServiceWithMockVerify({
    accountSid: Deno.env.get("TWILIO_ACCOUNT_SID")!,
    authToken: Deno.env.get("TWILIO_AUTH_TOKEN")!,
    phoneNumber: Deno.env.get("TWILIO_PHONE_NUMBER")!,
    verifyServiceSid: Deno.env.get("TWILIO_VERIFY_SERVICE_SID"),
  });
} else {
  console.log(`[Twilio] Initializing Real Twilio service (all features enabled)`);
  twilioService = new TwilioService({
    accountSid: Deno.env.get("TWILIO_ACCOUNT_SID")!,
    authToken: Deno.env.get("TWILIO_AUTH_TOKEN")!,
    phoneNumber: Deno.env.get("TWILIO_PHONE_NUMBER")!,
    verifyServiceSid: Deno.env.get("TWILIO_VERIFY_SERVICE_SID"),
  });
}

export const JournalEntry = Engine.instrumentConcept(new JournalEntryConcept(db));
export const CallWindow = Engine.instrumentConcept(new CallWindowConcept(db));
export const JournalPrompt = Engine.instrumentConcept(new JournalPromptConcept(db));
export const CallSession = Engine.instrumentConcept(new CallSessionConcept(db));
export const User = Engine.instrumentConcept(new UserConcept(db));
export const ReflectionSession = Engine.instrumentConcept(new ReflectionSessionConcept(db));
export const PhoneCall = Engine.instrumentConcept(new PhoneCallConcept(db));
export const CallScheduler = Engine.instrumentConcept(new CallSchedulerConcept(db));
export const Profile = Engine.instrumentConcept(new ProfileConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const UserAuthentication = Engine.instrumentConcept(new UserAuthenticationConcept(db, twilioService));
