// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { testDb } from "@utils/database.ts";

import JournalEntryConcept from "./JournalEntry/JournalEntryConcept.ts";
import CallWindowConcept from "./CallWindow/CallWindowConcept.ts";
import JournalPromptConcept from "./JournalPrompt/JournalPromptConcept.ts";
import CallSessionConcept from "./CallSession/CallSessionConcept.ts";
import UserConcept from "./User/UserConcept.ts";
import ReflectionSessionConcept from "./ReflectionSession/ReflectionSessionConcept.ts";
import ProfileConcept from "./Profile/ProfileConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import UserAuthenticationConcept from "./UserAuthentication/UserAuthenticationConcept.ts";

export type { default as JournalEntryConcept } from "./JournalEntry/JournalEntryConcept.ts";
export type { default as CallWindowConcept } from "./CallWindow/CallWindowConcept.ts";
export type { default as JournalPromptConcept } from "./JournalPrompt/JournalPromptConcept.ts";
export type { default as CallSessionConcept } from "./CallSession/CallSessionConcept.ts";
export type { default as UserConcept } from "./User/UserConcept.ts";
export type { default as ReflectionSessionConcept } from "./ReflectionSession/ReflectionSessionConcept.ts";
export type { default as ProfileConcept } from "./Profile/ProfileConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as UserAuthenticationConcept } from "./UserAuthentication/UserAuthenticationConcept.ts";

// Initialize the database connection
export const [db, client] = await testDb();

export const JournalEntry = Engine.instrumentConcept(new JournalEntryConcept(db));
export const CallWindow = Engine.instrumentConcept(new CallWindowConcept(db));
export const JournalPrompt = Engine.instrumentConcept(new JournalPromptConcept(db));
export const CallSession = Engine.instrumentConcept(new CallSessionConcept(db));
export const User = Engine.instrumentConcept(new UserConcept(db));
export const ReflectionSession = Engine.instrumentConcept(new ReflectionSessionConcept(db));
export const Profile = Engine.instrumentConcept(new ProfileConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const UserAuthentication = Engine.instrumentConcept(new UserAuthenticationConcept(db));
