// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually.


import type { Sync } from "@engine";

import * as sync_authentication from "./authentication.sync.ts";
import * as sync_callScheduler from "./callScheduler.sync.ts";

const allSyncs: Record<string, Sync> = {};


for (const [name, func] of Object.entries(sync_authentication)) {
  if (typeof func === "function") {
    allSyncs[`authentication.${name}`] = func as Sync;
  }
}

for (const [name, func] of Object.entries(sync_callScheduler)) {
  if (typeof func === "function") {
    allSyncs[`callScheduler.${name}`] = func as Sync;
  }
}

export default allSyncs;
